// src/parsers/codex.pest

WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
COMMENT    = _{ "//" ~ (!"\n" ~ ANY)* }

program = _{ SOI ~ stmt* ~ EOI }

stmt = { domain_block }

// Estructura General: nombre_dominio "nombre" { contenido }
// Usamos 'ident' para el keyword del dominio para que sea escalable (soporte 'subnet', 'optimize', etc. sin tocar este archivo)
domain_block = { ident ~ name? ~ "{" ~ domain_content ~ "}" }

// MAGIA RECURSIVA:
// El contenido es: Cualquier cosa que NO sea llave, O un bloque balanceado de llaves.
domain_content = { ( !("{" | "}") ~ ANY | "{" ~ domain_content ~ "}" )* }

// Primitivas
name       = @{ string_lit | ident }
string_lit = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
ident      = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }