WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
COMMENT    = _{ "//" ~ (!"\n" ~ ANY)* }
SEP        = _{ ","? } 

// CAMBIO PRINCIPAL: Eliminamos "| query_def"
// Ahora este parser solo espera UNA definición de sistema por bloque despachado.
linear_algebra_block = { SOI ~ system_def ~ EOI }

// ==========================================
// 1. DEFINICIÓN DE MODELO (Estado)
// ==========================================
system_def = { "LinearSystem" ~ model_id ~ "{" ~ (sys_property ~ SEP)* ~ "}" }

model_id     = { string_lit } 

sys_property = { prop_coeffs | prop_consts }
prop_coeffs  = { ("coefficients" | "A") ~ ":" ~ matrix_lit }
prop_consts  = { ("constants" | "b")    ~ ":" ~ matrix_lit }

// ==========================================
// 2. PRIMITIVAS Y MATRICES
// ==========================================
ident      = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
string_lit = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }

matrix_lit = { "[" ~ row ~ (row_sep ~ row)* ~ "]" }
row        = { number ~ (col_sep ~ number)* }
row_sep    = _{ ";" }
col_sep    = _{ "," }
number     = @{ "-"? ~ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT*)? }